name = "ddr-toolkit"
main = "worker.js"
compatibility_date = "2024-05-01"

[build]
command = "npm run build"

[site]
bucket = "./dist"


# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
