name = "ddr-toolkit"
main = "worker.js"           # keep whatever entry you’re actually using
compatibility_date = "2024-05-01"

[assets]
directory = "./dist"         # folder you want served
binding   = "ASSETS"         # this creates env.ASSETS

[build]
command = "npm run build"

[observability.logs]
enabled = true