name = "ddr-dan-tool"
pages_build_output_dir = "./dist"
compatibility_date = "2025-06-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ddr-toolkit"
# Reference the secret using a placeholder
database_id = "${DATABASE_ID}"