CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS settings (
  user_id INTEGER PRIMARY KEY,
  data TEXT
);
CREATE TABLE IF NOT EXISTS lists (
  user_id INTEGER PRIMARY KEY,
  data TEXT
);
